/**
 * PR Comment Renderer
 *
 * Generates a well-formatted Markdown risk report for GitHub PR comments.
 * Leads with what changed and what breaks — column-aware blast radius first,
 * governance triggers, reviewer/label automation, then per-entity details.
 */

import { RiskReport, RiskAssessment, RiskLevel, Decision } from '../risk/types';
import { ResolvedEntity } from '../openmetadata/types';
import { PatchAnalysis } from '../diff/patch-parser';
import { PRAggregateRisk } from '../risk/pr-aggregate';
import { ReviewerResult } from '../automation/workflow';
import { PolicyEvaluationResult } from '../policy/types';
import { generateRolloutGuidance } from '../policy/rollout-guidance';

/** Emoji mapping for risk levels */
const LEVEL_EMOJI: Record<RiskLevel, string> = {
  LOW: '🟢',
  MEDIUM: '🟡',
  HIGH: '🟠',
  CRITICAL: '🔴',
};

/** Emoji mapping for decisions */
const DECISION_EMOJI: Record<Decision, string> = {
  pass: '✅',
  warn: '⚠️',
  fail: '🚫',
};

/** Human-readable decision labels */
const DECISION_LABEL: Record<Decision, string> = {
  pass: 'Safe to merge',
  warn: 'Review required',
  fail: 'Block — manual review needed',
};

/**
 * Render context passed from the action to enrich the report
 * with automation results and policy decisions.
 */
export interface RenderContext {
  reviewerResult?: ReviewerResult;
  appliedLabels?: string[];
  /** Approval policy evaluation result */
  policyResult?: PolicyEvaluationResult;
}

/**
 * Render the full Markdown risk report.
 *
 * Section order (designed to lead with impact):
 * 1. Header + decision
 * 2. What Changed — changed columns + downstream breakage (the headline)
 * 3. Governance Triggers — OpenMetadata-native signals
 * 4. Automation — who was requested and why, what labels applied
 * 5. Overall Assessment — score table
 * 6. PR Escalation — compound risk (only if visible)
 * 7. Per-entity details (collapsible)
 * 8. Unresolved entities
 */
export function renderReport(
  report: RiskReport,
  entities: ResolvedEntity[],
  patchAnalyses?: PatchAnalysis[],
  aggregate?: PRAggregateRisk,
  context?: RenderContext
): string {
  const lines: string[] = [];
  const score = aggregate?.aggregateScore ?? report.maxScore;
  const decision = aggregate?.escalatedDecision ?? report.decision;
  const level = aggregate?.escalatedLevel ?? report.overallLevel;

  // ── 1. Header ──────────────────────────────────────────────────────
  lines.push('## 🔒 LineageLock Risk Report');
  lines.push('');
  lines.push(`${LEVEL_EMOJI[level]} **${level}** · ${score}/100 · ${DECISION_EMOJI[decision]} ${DECISION_LABEL[decision]}`);
  lines.push('');

  // ── 2. Approval Policies (top — this is the governance verdict) ────
  if (context?.policyResult && context.policyResult.triggeredPolicies.length > 0) {
    lines.push(renderApprovalPolicies(context.policyResult));
    lines.push('');
  }

  // ── 2. What Changed — lead with the column-aware blast radius ──────
  if (patchAnalyses && patchAnalyses.some(p => p.changedColumns.length > 0)) {
    lines.push(renderImpactSummary(patchAnalyses, entities));
    lines.push('');
  }

  // ── 3. Governance Triggers — OpenMetadata-native ───────────────────
  lines.push(renderGovernanceTriggers(entities));
  lines.push('');

  // ── 4. Automation — reviewers + labels with reasons ────────────────
  if (context && (context.reviewerResult || context.appliedLabels)) {
    lines.push(renderAutomation(context, entities));
    lines.push('');
  }

  // ── 5. Overall Assessment ──────────────────────────────────────────
  lines.push(renderOverallSummary(report, aggregate));
  lines.push('');

  // ── 6. PR-level aggregate (only if escalation produced visible change)
  if (aggregate && aggregate.factors.length > 0 &&
      aggregate.aggregateScore > aggregate.maxEntityScore) {
    lines.push(renderAggregateSection(aggregate));
    lines.push('');
  }

  // ── 7. Per-entity details ──────────────────────────────────────────
  for (let i = 0; i < report.assessments.length; i++) {
    const assessment = report.assessments[i];
    const entity = entities[i];
    const patch = patchAnalyses?.[i];
    lines.push(renderEntityDetail(assessment, entity, patch));
    lines.push('');
  }

  // ── 8. Unresolved entities ─────────────────────────────────────────
  const unresolved = entities.filter((e) => !e.found);
  if (unresolved.length > 0) {
    lines.push(renderUnresolvedEntities(unresolved));
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(
    `*Generated by [LineageLock](https://github.com/jayjoshix/incident-commander) · ` +
    `Powered by [OpenMetadata](https://open-metadata.org)*`
  );

  return lines.join('\n');
}

// ═════════════════════════════════════════════════════════════════════════════
//  Approval Policies
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Approval Policies section — shown at the top when policies are triggered.
 * Answers: "Who must approve this PR, and why — according to OpenMetadata?"
 */
function renderApprovalPolicies(policyResult: PolicyEvaluationResult): string {
  const lines: string[] = [];
  const blockCount = policyResult.triggeredPolicies.filter(p => p.severity === 'block').length;
  const warnCount = policyResult.triggeredPolicies.filter(p => p.severity === 'warn').length;

  if (policyResult.isBlocked) {
    lines.push(`### 🚫 Merge Blocked — ${blockCount} Approval Polic${blockCount === 1 ? 'y' : 'ies'} Require Sign-off`);
  } else {
    lines.push(`### ⚠️ ${warnCount} Governance Polic${warnCount === 1 ? 'y' : 'ies'} Triggered`);
  }
  lines.push('');

  for (const policy of policyResult.triggeredPolicies) {
    const icon = policy.severity === 'block' ? '🚫' : '⚠️';
    lines.push(`**${icon} ${policy.name}**`);
    lines.push(policy.reason);
    if (policy.requiredTeams.length > 0) {
      lines.push(`> Required: ${policy.requiredTeams.map(t => `team:${t}`).join(', ')}`);
    }
    if (policy.requiredUsers.length > 0) {
      lines.push(`> Required: ${policy.requiredUsers.map(u => `@${u}`).join(', ')}`);
    }
    if (policy.signals.length > 0) {
      lines.push(`> Signals: ${policy.signals.slice(0, 3).join(' · ')}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ═════════════════════════════════════════════════════════════════════════════
//  Section Renderers
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Section 2: Impact Summary — changed columns + downstream breakage + affected assets.
 * This is the headline: "what changed → what breaks → what stakeholders are affected."
 */
function renderImpactSummary(patchAnalyses: PatchAnalysis[], entities: ResolvedEntity[]): string {
  const lines: string[] = [];
  lines.push('### 🔬 What Changed → What Breaks');
  lines.push('');

  for (let i = 0; i < patchAnalyses.length; i++) {
    const pa = patchAnalyses[i];
    if (pa.changedColumns.length === 0) continue;
    const entity = entities[i];

    // Changed columns
    const colNames = pa.changedColumns.map(c => `\`${c.name}\``).join(', ');
    lines.push(`**Changed columns** in \`${pa.filePath}\`: ${colNames}`);
    lines.push('');

    // Downstream column breakage (from column lineage intersection)
    if (entity?.downstream?.columnImpact && entity.downstream.columnImpact.length > 0) {
      const changedNames = new Set(pa.changedColumns.map(c => c.name.toLowerCase()));
      const impacted = entity.downstream.columnImpact.filter(ci =>
        ci.fromColumns.some(fc => {
          const colName = fc.split('.').pop()?.toLowerCase() || '';
          return changedNames.has(colName);
        })
      );
      if (impacted.length > 0) {
        lines.push('**Downstream breakage:**');
        for (const ci of impacted.slice(0, 8)) {
          const from = ci.fromColumns.map(c => c.split('.').pop()).join(', ');
          const to = ci.toColumn.split('.').pop();
          const toEntityShort = ci.toEntity.split('.').pop();
          lines.push(`- \`${from}\` → \`${to}\` in \`${toEntityShort}\``);
        }
        lines.push('');
      }
    }

    // Affected business assets (dashboards, ML models)
    if (entity?.downstream) {
      const assets: string[] = [];
      for (const d of entity.downstream.dashboards) {
        assets.push(`📊 ${d.name}`);
      }
      for (const m of entity.downstream.mlModels) {
        assets.push(`🤖 ${m.name}`);
      }
      if (assets.length > 0) {
        lines.push(`**Affected assets:** ${assets.join(', ')}`);
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

/**
 * Section 3: Governance Triggers — everything OpenMetadata knows about why this matters.
 */
function renderGovernanceTriggers(entities: ResolvedEntity[]): string {
  const lines: string[] = [];
  lines.push('### 🏛️ Governance Triggers');
  lines.push('');
  lines.push('*Signals from OpenMetadata that drive this assessment:*');
  lines.push('');

  const triggers: string[] = [];

  // Tier
  const tiers = entities
    .filter(e => e.entity?.tier)
    .map(e => `\`${e.entity!.tier}\` on \`${e.entity!.name}\``);
  if (tiers.length > 0) {
    triggers.push(`🏷️ **Tier:** ${tiers.join(', ')}`);
  }

  // PII/GDPR/Sensitive tags
  const sensitiveEntities = entities.filter(e => {
    const allTags = [
      ...(e.entity?.tags || []),
      ...(e.entity?.columns || []).flatMap(c => c.tags || []),
    ];
    return allTags.some(t =>
      t.tagFQN.includes('PII.Sensitive') ||
      t.tagFQN.includes('GDPR') ||
      t.tagFQN.includes('PHI') ||
      t.tagFQN.includes('PCI') ||
      t.tagFQN.includes('PersonalData')
    );
  });
  if (sensitiveEntities.length > 0) {
    const tagList = sensitiveEntities.flatMap(e => {
      const allTags = [
        ...(e.entity?.tags || []),
        ...(e.entity?.columns || []).flatMap(c => c.tags || []),
      ];
      return allTags
        .filter(t =>
          t.tagFQN.includes('PII.Sensitive') ||
          t.tagFQN.includes('GDPR') ||
          t.tagFQN.includes('PHI') ||
          t.tagFQN.includes('PCI') ||
          t.tagFQN.includes('PersonalData')
        )
        .map(t => `\`${t.tagFQN}\``);
    });
    const uniqueTags = [...new Set(tagList)];
    triggers.push(`🔐 **Sensitive tags:** ${uniqueTags.join(', ')}`);
  }

  // Glossary terms
  const glossaryTerms = entities.flatMap(e => e.glossaryTerms || []);
  if (glossaryTerms.length > 0) {
    const unique = [...new Set(glossaryTerms)].map(g => `\`${g}\``);
    triggers.push(`📖 **Glossary terms:** ${unique.join(', ')}`);
  }

  // Contract status
  const contracts = entities.filter(e => e.contract?.hasContract);
  if (contracts.length > 0) {
    for (const e of contracts) {
      const c = e.contract!;
      const status = c.failingTests > 0 ? '🔴 Failing' : '🟢 Passing';
      const source = c.contractSource === 'official' ? 'Official API' : 'Test Suite';
      triggers.push(`📄 **Contract:** ${status} (${c.totalTests - c.failingTests}/${c.totalTests} tests) · Source: ${source}`);
    }
  }

  // Owner/team
  const owners = entities
    .filter(e => e.entity?.owner)
    .map(e => `**${e.entity!.owner!.displayName || e.entity!.owner!.name}** (${e.entity!.owner!.type})`);
  const ownerUnique = [...new Set(owners)];
  if (ownerUnique.length > 0) {
    triggers.push(`👤 **Owner:** ${ownerUnique.join(', ')}`);
  }

  if (triggers.length > 0) {
    lines.push(...triggers.map(t => `- ${t}`));
  } else {
    lines.push('- No governance signals detected');
  }

  return lines.join('\n');
}

/**
 * Section 4: Automation — who was requested and why, what labels applied and why.
 */
function renderAutomation(context: RenderContext, entities: ResolvedEntity[]): string {
  const lines: string[] = [];
  lines.push('### ⚡ Automation');
  lines.push('');

  // Reviewers with reasons
  if (context.reviewerResult) {
    const { users, teams } = context.reviewerResult;
    if (users.length > 0 || teams.length > 0) {
      lines.push('**Requested reviewers:**');
      for (const user of users) {
        const ownerEntity = entities.find(e =>
          e.entity?.owner?.name === user || e.entity?.owner?.displayName === user
        );
        const reason = ownerEntity
          ? `this asset is owned by \`${ownerEntity.entity!.owner!.displayName || ownerEntity.entity!.owner!.name}\` in OpenMetadata`
          : 'mapped via ownerMapping config';
        lines.push(`- @${user} — *${reason}*`);
      }
      for (const team of teams) {
        const ownerEntity = entities.find(e =>
          e.entity?.owner?.type === 'team' && e.entity?.owner?.name === team
        );
        const reason = ownerEntity
          ? `this asset is owned by **${ownerEntity.entity!.owner!.displayName || ownerEntity.entity!.owner!.name}** in OpenMetadata`
          : 'team ownership detected in OpenMetadata';
        lines.push(`- team:${team} — *${reason}*`);
      }
      lines.push('');
    }
  }

  // Labels with reasons
  if (context.appliedLabels && context.appliedLabels.length > 0) {
    lines.push('**Applied labels:**');
    for (const label of context.appliedLabels) {
      const reason = getLabelReason(label);
      lines.push(`- \`${label}\` — *${reason}*`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/** Map label names to human-readable reasons */
function getLabelReason(label: string): string {
  const reasons: Record<string, string> = {
    'lineagelock:tier1-change': 'entity has Tier 1/Tier 2 classification in OpenMetadata',
    'lineagelock:pii-impact': 'column tags include PII, GDPR, or sensitive data classifications',
    'lineagelock:contract-risk': 'data contract has failing quality tests',
    'lineagelock:column-breakage': 'structural column changes detected in PR patches',
    'lineagelock:high-risk': 'risk score ≥ 60',
    'lineagelock:no-owner': 'entity has no owner assigned in OpenMetadata',
  };
  return reasons[label] || 'governance condition triggered';
}

/**
 * Section 5: Overall Assessment table.
 */
function renderOverallSummary(report: RiskReport, aggregate?: PRAggregateRisk): string {
  const lines: string[] = [];
  const score = aggregate?.aggregateScore ?? report.maxScore;
  const decision = aggregate?.escalatedDecision ?? report.decision;
  const level = aggregate?.escalatedLevel ?? report.overallLevel;

  lines.push('<details>');
  lines.push('<summary>📊 Detailed Scoring</summary>');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| **Risk Score** | ${LEVEL_EMOJI[level]} **${score}/100** (${level}) |`);
  lines.push(`| **Decision** | ${DECISION_EMOJI[decision]} ${DECISION_LABEL[decision]} |`);
  lines.push(`| **Entities Analyzed** | ${report.summary.totalEntities} |`);
  lines.push(`| **Resolved** | ${report.summary.resolvedEntities} |`);
  lines.push(`| **Downstream Impact** | ${report.summary.totalDownstream} entities (${report.summary.totalDashboards} dashboards, ${report.summary.totalMlModels} ML models) |`);

  if (aggregate && aggregate.aggregateScore > aggregate.maxEntityScore) {
    lines.push('');
    lines.push(`> ⚠️ PR-level escalation: score elevated from ${aggregate.maxEntityScore} → ${aggregate.aggregateScore} due to compound risk factors`);
  }

  lines.push('');
  lines.push('</details>');

  return lines.join('\n');
}

/**
 * Section 6: PR-level aggregate risk factors (only shown when escalation has visible effect).
 */
function renderAggregateSection(aggregate: PRAggregateRisk): string {
  const lines: string[] = [];
  lines.push('<details>');
  lines.push('<summary>📈 PR-Level Risk Escalation</summary>');
  lines.push('');
  lines.push('| Factor | Count | Escalation |');
  lines.push('|--------|-------|------------|');
  for (const f of aggregate.factors) {
    lines.push(`| ${f.name} | ${f.count} | +${f.escalation} pts |`);
  }
  lines.push('');
  lines.push(`**Total escalation:** +${aggregate.aggregateScore - aggregate.maxEntityScore} points`);
  lines.push('');
  lines.push('</details>');
  return lines.join('\n');
}

/**
 * Section 7: Per-entity detail (collapsible).
 */
function renderEntityDetail(
  assessment: RiskAssessment,
  entity: ResolvedEntity,
  patch?: PatchAnalysis
): string {
  const lines: string[] = [];
  const emoji = LEVEL_EMOJI[assessment.level];

  lines.push(`### ${emoji} \`${assessment.filePath}\``);
  lines.push('');
  lines.push(`**Entity:** \`${assessment.fqn}\``);
  lines.push(`**Score:** ${assessment.score}/100 (${assessment.level})`);
  lines.push('');

  if (!assessment.entityFound) {
    lines.push(`> ⚠️ Entity not found in OpenMetadata: ${assessment.error || 'Unknown error'}`);
    return lines.join('\n');
  }

  // Risk factors table
  lines.push('<details>');
  lines.push(`<summary>Risk Factors (${assessment.factors.filter(f => f.triggered).length}/${assessment.factors.length} triggered)</summary>`);
  lines.push('');
  lines.push('| Factor | Points | Status | Detail |');
  lines.push('|--------|--------|--------|--------|');
  for (const factor of assessment.factors) {
    const status = factor.triggered ? '🔴 Triggered' : '✅ Clear';
    lines.push(
      `| ${factor.name} | ${factor.points}/${factor.maxPoints} | ${status} | ${factor.detail || '—'} |`
    );
  }
  lines.push('');
  lines.push('</details>');

  // Downstream assets
  if (entity.downstream && entity.downstream.total > 0) {
    lines.push('');
    lines.push('<details>');
    lines.push(`<summary>Downstream Assets (${entity.downstream.total})</summary>`);
    lines.push('');
    if (entity.downstream.dashboards.length > 0) {
      lines.push('**Dashboards:**');
      for (const d of entity.downstream.dashboards) {
        lines.push(`- 📊 \`${d.fullyQualifiedName}\``);
      }
    }
    if (entity.downstream.mlModels.length > 0) {
      lines.push('**ML Models:**');
      for (const m of entity.downstream.mlModels) {
        lines.push(`- 🤖 \`${m.fullyQualifiedName}\``);
      }
    }
    if (entity.downstream.tables.length > 0) {
      lines.push('**Tables:**');
      for (const t of entity.downstream.tables) {
        lines.push(`- 📋 \`${t.fullyQualifiedName}\``);
      }
    }
    if (entity.downstream.pipelines.length > 0) {
      lines.push('**Pipelines:**');
      for (const p of entity.downstream.pipelines) {
        lines.push(`- ⚙️ \`${p.fullyQualifiedName}\``);
      }
    }
    // Column-level lineage
    if (entity.downstream.columnImpact.length > 0) {
      lines.push('');
      lines.push(`**Column Lineage (${entity.downstream.columnImpact.length} mappings):**`);
      for (const ci of entity.downstream.columnImpact.slice(0, 8)) {
        const from = ci.fromColumns.map(c => c.split('.').pop()).join(', ');
        const to = ci.toColumn.split('.').pop();
        lines.push(`- \`${from}\` → \`${to}\` in \`${ci.toEntity}\``);
      }
      if (entity.downstream.columnImpact.length > 8) {
        lines.push(`- *...and ${entity.downstream.columnImpact.length - 8} more*`);
      }
    }
    lines.push('');
    lines.push('</details>');
  }

  // Contract status (with source)
  if (entity.contract) {
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Contract Status</summary>');
    lines.push('');
    if (entity.contract.hasContract) {
      const status = entity.contract.failingTests > 0 ? '🔴 Failing' : '🟢 Passing';
      const source = entity.contract.contractSource === 'official' ? 'Official API' : 'Test Suite';
      lines.push(`- **Status:** ${status}`);
      lines.push(`- **Source:** ${source}`);
      lines.push(`- **Suite:** \`${entity.contract.testSuiteName}\``);
      lines.push(`- **Tests:** ${entity.contract.totalTests - entity.contract.failingTests}/${entity.contract.totalTests} passing`);
      if (entity.contract.tests) {
        for (const test of entity.contract.tests) {
          const icon = test.status === 'Success' ? '✅' : test.status === 'Failed' ? '❌' : '⚪';
          lines.push(`  - ${icon} ${test.name}`);
        }
      }
    } else {
      lines.push('- No data contract defined for this asset');
    }
    lines.push('');
    lines.push('</details>');
  }

  // Active quality issues from OpenMetadata observability
  if (entity.activeQualityIssues && entity.activeQualityIssues.length > 0) {
    lines.push('');
    lines.push('> ⚠️ **Active Quality Issues (from OpenMetadata)**');
    lines.push('> ');
    lines.push('> This asset already has failing quality tests. Merging now adds risk on top of existing issues.');
    lines.push('> ');
    for (const issue of entity.activeQualityIssues.slice(0, 5)) {
      const age = issue.timestamp
        ? formatAge(issue.timestamp)
        : 'unknown age';
      lines.push(`> - ❌ \`${issue.name}\` — ${issue.failureReason || issue.status} *(${age})*`);
    }
  }

  // Rollout guidance (only when structural column changes exist with downstream impact)
  if (patch && entity.downstream?.columnImpact?.length) {
    const guidance = generateRolloutGuidance(patch, entity);
    if (guidance.length > 0) {
      lines.push('');
      lines.push('<details>');
      lines.push('<summary>📋 Safe Rollout Guidance</summary>');
      lines.push('');
      lines.push('*These columns flow into downstream assets. To change them safely:*');
      lines.push('');
      for (const g of guidance) {
        lines.push(`**Column \`${g.columnName}\`** (${g.changeType}) — affects: ${g.downstreamAssets.slice(0, 3).join(', ')}`);
        for (const step of g.steps) {
          lines.push(`${step.step}. **${step.action}** — ${step.detail}`);
        }
        lines.push('');
      }
      lines.push('</details>');
    }
  }

  return lines.join('\n');
}

function formatAge(isoTimestamp: string): string {
  const ms = Date.now() - new Date(isoTimestamp).getTime();
  const hours = Math.floor(ms / 3600000);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}


/**
 * Render section for unresolved entities.
 */
function renderUnresolvedEntities(unresolved: ResolvedEntity[]): string {
  const lines: string[] = [];

  lines.push('### ⚠️ Unresolved Entities');
  lines.push('');
  lines.push('The following changed files could not be resolved to OpenMetadata entities:');
  lines.push('');
  for (const e of unresolved) {
    lines.push(`- \`${e.filePath}\` → \`${e.fqn}\` — ${e.error || 'Not found'}`);
  }
  lines.push('');
  lines.push(
    '> Check your `.lineagelock.json` naming convention or add explicit mappings.'
  );

  return lines.join('\n');
}

/**
 * Render a compact single-line summary (for action output).
 */
export function renderCompactSummary(report: RiskReport, aggregate?: PRAggregateRisk): string {
  const level = aggregate?.escalatedLevel ?? report.overallLevel;
  const score = aggregate?.aggregateScore ?? report.maxScore;
  const decision = aggregate?.escalatedDecision ?? report.decision;
  const emoji = LEVEL_EMOJI[level];
  return `${emoji} LineageLock: ${level} (${score}/100) — ${DECISION_LABEL[decision]}`;
}
