/**
 * PR Comment Renderer
 *
 * Generates a well-formatted Markdown risk report for GitHub PR comments.
 * Surfaces column-level lineage, glossary terms, and aggregate PR risk.
 */

import { RiskReport, RiskAssessment, RiskLevel, Decision } from '../risk/types';
import { ResolvedEntity } from '../openmetadata/types';
import { PatchAnalysis } from '../diff/patch-parser';
import { PRAggregateRisk } from '../risk/pr-aggregate';

/** Emoji mapping for risk levels */
const LEVEL_EMOJI: Record<RiskLevel, string> = {
  LOW: '🟢',
  MEDIUM: '🟡',
  HIGH: '🟠',
  CRITICAL: '🔴',
};

/** Emoji mapping for decisions */
const DECISION_EMOJI: Record<Decision, string> = {
  pass: '✅',
  warn: '⚠️',
  fail: '🚫',
};

/** Human-readable decision labels */
const DECISION_LABEL: Record<Decision, string> = {
  pass: 'Safe to merge',
  warn: 'Review required',
  fail: 'Block — manual review needed',
};

/**
 * Render the full Markdown risk report.
 */
export function renderReport(
  report: RiskReport,
  entities: ResolvedEntity[],
  patchAnalyses?: PatchAnalysis[],
  aggregate?: PRAggregateRisk
): string {
  const lines: string[] = [];

  // Header
  lines.push('## 🔒 LineageLock Risk Report');
  lines.push('');

  // Overall summary (use aggregate if available)
  lines.push(renderOverallSummary(report, aggregate));
  lines.push('');

  // PR-level aggregate (if escalated)
  if (aggregate && aggregate.factors.length > 0) {
    lines.push(renderAggregateSection(aggregate));
    lines.push('');
  }

  // Blast radius summary
  lines.push(renderBlastRadiusSummary(report));
  lines.push('');

  // Changed columns summary (from patch analysis)
  if (patchAnalyses && patchAnalyses.some(p => p.changedColumns.length > 0)) {
    lines.push(renderChangedColumnsSummary(patchAnalyses, entities));
    lines.push('');
  }

  // Per-entity details
  for (let i = 0; i < report.assessments.length; i++) {
    const assessment = report.assessments[i];
    const entity = entities[i];
    const patch = patchAnalyses?.[i];
    lines.push(renderEntityDetail(assessment, entity, patch));
    lines.push('');
  }

  // Unresolved entities
  const unresolved = entities.filter((e) => !e.found);
  if (unresolved.length > 0) {
    lines.push(renderUnresolvedEntities(unresolved));
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(
    `*Generated by [LineageLock](https://github.com/jayjoshix/incident-commander) · ` +
    `Powered by [OpenMetadata](https://open-metadata.org)*`
  );

  return lines.join('\n');
}

/**
 * Render the overall summary section.
 */
function renderOverallSummary(report: RiskReport, aggregate?: PRAggregateRisk): string {
  const lines: string[] = [];
  const score = aggregate?.aggregateScore ?? report.maxScore;
  const decision = aggregate?.escalatedDecision ?? report.decision;
  const level = aggregate?.escalatedLevel ?? report.overallLevel;
  const emoji = LEVEL_EMOJI[level];
  const decisionEmoji = DECISION_EMOJI[decision];
  const decisionLabel = DECISION_LABEL[decision];

  lines.push('### Overall Assessment');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| **Risk Score** | ${emoji} **${score}/100** (${level}) |`);
  lines.push(`| **Decision** | ${decisionEmoji} ${decisionLabel} |`);
  lines.push(`| **Entities Analyzed** | ${report.summary.totalEntities} |`);
  lines.push(`| **Resolved** | ${report.summary.resolvedEntities} |`);
  lines.push(`| **Unresolved** | ${report.summary.unresolvedEntities} |`);

  if (aggregate && aggregate.aggregateScore > aggregate.maxEntityScore) {
    lines.push('');
    lines.push(`> ⚠️ PR-level escalation: score elevated from ${aggregate.maxEntityScore} → ${aggregate.aggregateScore} due to compound risk factors`);
  }

  return lines.join('\n');
}

/**
 * Render PR-level aggregate risk factors.
 */
function renderAggregateSection(aggregate: PRAggregateRisk): string {
  const lines: string[] = [];
  lines.push('<details>');
  lines.push('<summary>📊 PR-Level Risk Escalation</summary>');
  lines.push('');
  lines.push('| Factor | Count | Escalation |');
  lines.push('|--------|-------|------------|');
  for (const f of aggregate.factors) {
    lines.push(`| ${f.name} | ${f.count} | +${f.escalation} pts |`);
  }
  lines.push('');
  lines.push(`**Total escalation:** +${aggregate.aggregateScore - aggregate.maxEntityScore} points`);
  lines.push('');
  lines.push('</details>');
  return lines.join('\n');
}

/**
 * Render the blast radius summary.
 */
function renderBlastRadiusSummary(report: RiskReport): string {
  const lines: string[] = [];
  const s = report.summary;

  lines.push('### 💥 Blast Radius');
  lines.push('');
  lines.push('| Category | Count |');
  lines.push('|----------|-------|');
  lines.push(`| Total downstream entities | ${s.totalDownstream} |`);
  lines.push(`| Dashboards impacted | ${s.totalDashboards} |`);
  lines.push(`| ML Models impacted | ${s.totalMlModels} |`);

  return lines.join('\n');
}

/**
 * Render changed columns summary across all files.
 */
function renderChangedColumnsSummary(
  patchAnalyses: PatchAnalysis[],
  entities: ResolvedEntity[]
): string {
  const lines: string[] = [];
  lines.push('### 🔬 Column-Level Impact');
  lines.push('');

  for (let i = 0; i < patchAnalyses.length; i++) {
    const pa = patchAnalyses[i];
    if (pa.changedColumns.length === 0) continue;

    lines.push(`**\`${pa.filePath}\`** — ${pa.changeDescription}`);

    for (const col of pa.changedColumns) {
      const icon = col.changeType === 'added' ? '➕' :
        col.changeType === 'removed' ? '➖' :
        col.changeType === 'renamed' ? '🔄' : '✏️';
      const conf = col.confidence === 'high' ? '' : ` *(${col.confidence} confidence)*`;
      lines.push(`- ${icon} \`${col.name}\` — ${col.changeType}${conf}`);
    }

    // Cross-reference with column lineage
    const entity = entities[i];
    if (entity?.downstream?.columnImpact && entity.downstream.columnImpact.length > 0) {
      const changedNames = new Set(pa.changedColumns.map(c => c.name.toLowerCase()));
      const impacted = entity.downstream.columnImpact.filter(ci =>
        ci.fromColumns.some(fc => {
          const colName = fc.split('.').pop()?.toLowerCase() || '';
          return changedNames.has(colName);
        })
      );
      if (impacted.length > 0) {
        lines.push('');
        lines.push('  **⚡ Downstream column impact:**');
        for (const ci of impacted.slice(0, 5)) {
          lines.push(`  - \`${ci.fromColumns.map(c => c.split('.').pop()).join(', ')}\` → \`${ci.toColumn.split('.').pop()}\` in \`${ci.toEntity}\``);
        }
        if (impacted.length > 5) {
          lines.push(`  - *...and ${impacted.length - 5} more*`);
        }
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Render detail for a single assessed entity.
 */
function renderEntityDetail(
  assessment: RiskAssessment,
  entity: ResolvedEntity,
  patch?: PatchAnalysis
): string {
  const lines: string[] = [];
  const emoji = LEVEL_EMOJI[assessment.level];

  lines.push(`### ${emoji} \`${assessment.filePath}\``);
  lines.push('');
  lines.push(`**Entity:** \`${assessment.fqn}\``);
  lines.push(`**Score:** ${assessment.score}/100 (${assessment.level})`);
  lines.push('');

  if (!assessment.entityFound) {
    lines.push(`> ⚠️ Entity not found in OpenMetadata: ${assessment.error || 'Unknown error'}`);
    return lines.join('\n');
  }

  // Risk factors table
  lines.push('<details>');
  lines.push(`<summary>Risk Factors (${assessment.factors.filter(f => f.triggered).length}/${assessment.factors.length} triggered)</summary>`);
  lines.push('');
  lines.push('| Factor | Points | Status | Detail |');
  lines.push('|--------|--------|--------|--------|');
  for (const factor of assessment.factors) {
    const status = factor.triggered ? '🔴 Triggered' : '✅ Clear';
    lines.push(
      `| ${factor.name} | ${factor.points}/${factor.maxPoints} | ${status} | ${factor.detail || '—'} |`
    );
  }
  lines.push('');
  lines.push('</details>');

  // Downstream assets
  if (entity.downstream && entity.downstream.total > 0) {
    lines.push('');
    lines.push('<details>');
    lines.push(`<summary>Downstream Assets (${entity.downstream.total})</summary>`);
    lines.push('');
    if (entity.downstream.dashboards.length > 0) {
      lines.push('**Dashboards:**');
      for (const d of entity.downstream.dashboards) {
        lines.push(`- 📊 \`${d.fullyQualifiedName}\``);
      }
    }
    if (entity.downstream.mlModels.length > 0) {
      lines.push('**ML Models:**');
      for (const m of entity.downstream.mlModels) {
        lines.push(`- 🤖 \`${m.fullyQualifiedName}\``);
      }
    }
    if (entity.downstream.tables.length > 0) {
      lines.push('**Tables:**');
      for (const t of entity.downstream.tables) {
        lines.push(`- 📋 \`${t.fullyQualifiedName}\``);
      }
    }
    if (entity.downstream.pipelines.length > 0) {
      lines.push('**Pipelines:**');
      for (const p of entity.downstream.pipelines) {
        lines.push(`- ⚙️ \`${p.fullyQualifiedName}\``);
      }
    }
    // Column-level lineage
    if (entity.downstream.columnImpact.length > 0) {
      lines.push('');
      lines.push(`**Column Lineage (${entity.downstream.columnImpact.length} mappings):**`);
      for (const ci of entity.downstream.columnImpact.slice(0, 8)) {
        const from = ci.fromColumns.map(c => c.split('.').pop()).join(', ');
        const to = ci.toColumn.split('.').pop();
        lines.push(`- \`${from}\` → \`${to}\` in \`${ci.toEntity}\``);
      }
      if (entity.downstream.columnImpact.length > 8) {
        lines.push(`- *...and ${entity.downstream.columnImpact.length - 8} more*`);
      }
    }
    lines.push('');
    lines.push('</details>');
  }

  // Governance info
  if (entity.entity) {
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Governance</summary>');
    lines.push('');
    const e = entity.entity;
    lines.push(`- **Owner:** ${e.owner ? `${e.owner.displayName || e.owner.name} (${e.owner.type})` : '⚠️ No owner assigned'}`);
    lines.push(`- **Tier:** ${e.tier || 'Not classified'}`);
    if (e.tags && e.tags.length > 0) {
      lines.push(`- **Tags:** ${e.tags.map((t) => `\`${t.tagFQN}\``).join(', ')}`);
    } else {
      lines.push('- **Tags:** None');
    }
    // Glossary terms
    if (entity.glossaryTerms && entity.glossaryTerms.length > 0) {
      lines.push(`- **Glossary Terms:** ${entity.glossaryTerms.map(g => `\`${g}\``).join(', ')}`);
    }
    lines.push('');
    lines.push('</details>');
  }

  // Contract status
  if (entity.contract) {
    lines.push('');
    lines.push('<details>');
    lines.push('<summary>Contract Status</summary>');
    lines.push('');
    if (entity.contract.hasContract) {
      const status = entity.contract.failingTests > 0 ? '🔴 Failing' : '🟢 Passing';
      lines.push(`- **Status:** ${status}`);
      lines.push(`- **Suite:** \`${entity.contract.testSuiteName}\``);
      lines.push(`- **Tests:** ${entity.contract.totalTests - entity.contract.failingTests}/${entity.contract.totalTests} passing`);
      if (entity.contract.tests) {
        for (const test of entity.contract.tests) {
          const icon = test.status === 'Success' ? '✅' : test.status === 'Failed' ? '❌' : '⚪';
          lines.push(`  - ${icon} ${test.name}`);
        }
      }
    } else {
      lines.push('- No data contract defined for this asset');
    }
    lines.push('');
    lines.push('</details>');
  }

  // Owner action recommendation
  if (entity.entity?.owner) {
    lines.push('');
    lines.push(`📬 **Action:** Request review from **${entity.entity.owner.displayName || entity.entity.owner.name}** (${entity.entity.owner.type})`);
  } else if (entity.found) {
    lines.push('');
    lines.push('📬 **Action:** ⚠️ No owner — assign an owner in OpenMetadata before merging');
  }

  return lines.join('\n');
}

/**
 * Render section for unresolved entities.
 */
function renderUnresolvedEntities(unresolved: ResolvedEntity[]): string {
  const lines: string[] = [];

  lines.push('### ⚠️ Unresolved Entities');
  lines.push('');
  lines.push('The following changed files could not be resolved to OpenMetadata entities:');
  lines.push('');
  for (const e of unresolved) {
    lines.push(`- \`${e.filePath}\` → \`${e.fqn}\` — ${e.error || 'Not found'}`);
  }
  lines.push('');
  lines.push(
    '> Check your `.lineagelock.json` naming convention or add explicit mappings.'
  );

  return lines.join('\n');
}

/**
 * Render a compact single-line summary (for action output).
 */
export function renderCompactSummary(report: RiskReport, aggregate?: PRAggregateRisk): string {
  const level = aggregate?.escalatedLevel ?? report.overallLevel;
  const score = aggregate?.aggregateScore ?? report.maxScore;
  const decision = aggregate?.escalatedDecision ?? report.decision;
  const emoji = LEVEL_EMOJI[level];
  return `${emoji} LineageLock: ${level} (${score}/100) — ${DECISION_LABEL[decision]}`;
}
